development:
  adapter: postgresql
  encoding: unicode
  database: app_with_react_development
  pool: 5
  username: tomek
  password: tomek


test:
  adapter: postgresql
  encoding: unicode
  database: app_with_react_test
  pool: 5
  username: tomek
  password: tomek
